#DigiWorld Autosave
#Thu May 14 22:38:37 CST 2026
aceJazzDefeated=false
alphaBossDefeated=false
battledWoltrix=false
beastCards=5
collapseStarted=false
equippedBeasts=Kyoflare,Nokami,Voltchu
hasChallengeTicket=false
hasGWatch=true
hasMechDriver=true
hasTalkedToChiefRei=true
hasTalkedToGeneral=true
hasTalkedToProfessor=true
objective=Locate the Wild Vineratops using your G-Watch
ownedBeasts=Kyoflare,Nokami,Voltchu
questStage=5
starterChosen=true
starterSelectionDone=true
trialCompleted=false
worldIndex=1
