#DigiWorld Autosave
#Thu May 14 16:30:16 PST 2026
aceJazzDefeated=false
alphaBossDefeated=false
battledWoltrix=false
beastCards=0
collapseStarted=false
equippedBeasts=
hasChallengeTicket=false
hasGWatch=false
hasMechDriver=false
hasTalkedToChiefRei=false
hasTalkedToGeneral=false
hasTalkedToProfessor=false
objective=Find Professor Alfred
ownedBeasts=
questStage=0
starterChosen=false
starterSelectionDone=false
trialCompleted=false
worldIndex=0
