#DigiWorld Autosave
#Fri May 15 08:22:07 SGT 2026
aceJazzDefeated=false
alphaBossDefeated=false
battledWoltrix=false
beastCards=5
coins=0
collapseStarted=false
equippedBeasts=Kyoflare,All Mighty,Kingmantis
hasChallengeTicket=false
hasGWatch=true
hasMechDriver=true
hasTalkedToChiefRei=false
hasTalkedToGeneral=true
hasTalkedToProfessor=true
objective=Go to the teleport door
ownedBeasts=Kyoflare,All Mighty,Kingmantis
questStage=3
starterChosen=true
starterSelectionDone=true
trialCompleted=false
worldIndex=0
